version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/development/web
      - .env/development/database
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack-dev-server

volumes:
  db_data:
  gem_cache:
